"""
WhatsApp Notification System via Twilio

Sends professional, short WhatsApp alerts to user for important job events:
- Interview scheduled
- Offer received  
- Follow-up reminder (no response after X days)

IMPORTANT: These are ALERTS TO THE USER, not messages to recruiters.
Messages are generated by Groq (never hardcoded).
"""

from twilio.rest import Client
from groq import Groq
import os
from dotenv import load_dotenv
import logging

load_dotenv()

# Initialize clients
twilio_client = Client(
    os.getenv("TWILIO_ACCOUNT_SID"),
    os.getenv("TWILIO_AUTH_TOKEN")
)
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

# Twilio WhatsApp endpoints (from .env)
WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "whatsapp:+14155238886")
WHATSAPP_TO = os.getenv("TWILIO_WHATSAPP_TO")

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def generate_whatsapp_message(event_type: str, company: str, role: str, 
                             days_since_update: int = 0, status: str = "") -> str:
    """
    Use Groq to generate professional WhatsApp notification.
    
    Args:
        event_type: "interview_scheduled", "offer_received", "follow_up_reminder"
        company: Company name
        role: Job role
        days_since_update: Days since last update (for follow-up reminders)
        status: Current job status
    
    Returns:
        Generated WhatsApp message (≤ 5 lines, professional tone)
    """
    
    if event_type == "interview_scheduled":
        prompt = f"""
You are a professional career assistant. Generate a SHORT WhatsApp notification (≤ 5 lines) 
alerting the user about a scheduled interview.

Company: {company}
Role: {role}

The message should be:
- Professional, brief, no emojis
- Congratulatory but factual
- Action-oriented (e.g., "Prepare for technical round")

Respond with ONLY the WhatsApp message, no additional text.
"""
    
    elif event_type == "offer_received":
        prompt = f"""
You are a professional career assistant. Generate a SHORT WhatsApp notification (≤ 5 lines)
alerting the user about a job offer received.

Company: {company}
Role: {role}

The message should be:
- Professional, excited but not over-the-top
- Mention no emojis
- Suggest next action (review offer, negotiate, accept)

Respond with ONLY the WhatsApp message, no additional text.
"""
    
    elif event_type == "follow_up_reminder":
        prompt = f"""
You are a professional career assistant. Generate a SHORT WhatsApp notification (≤ 5 lines)
reminding the user to follow up on a pending application.

Company: {company}
Role: {role}
Days waiting: {days_since_update} days

The message should be:
- Professional reminder tone
- Mention the company and role
- Suggest sending a polite follow-up email

Respond with ONLY the WhatsApp message, no additional text.
"""
    
    else:
        return ""
    
    try:
        response = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.7,
            max_tokens=150
        )
        
        message = response.choices[0].message.content.strip()
        
        # Truncate if exceeds 160 chars (WhatsApp single SMS)
        if len(message) > 160:
            message = message[:157] + "..."
        
        return message
    
    except Exception as e:
        logger.error(f"Error generating WhatsApp message: {e}")
        return f"Alert: {event_type} for {role} at {company}"


def send_whatsapp_notification(message: str, retry_on_fail: bool = True) -> bool:
    """
    Send WhatsApp notification via Twilio.
    
    Args:
        message: Message text to send
        retry_on_fail: Whether to retry on failure
    
    Returns:
        True if successful, False otherwise
    """
    
    # Validate credentials
    if not all([WHATSAPP_FROM, WHATSAPP_TO]):
        logger.warning("WhatsApp credentials incomplete. Skipping notification.")
        return False
    
    try:
        msg = twilio_client.messages.create(
            from_=WHATSAPP_FROM,
            to=WHATSAPP_TO,
            body=message
        )
        
        logger.info(f"✓ WhatsApp sent (SID: {msg.sid})")
        return True
    
    except Exception as e:
        logger.error(f"✗ Failed to send WhatsApp: {e}")
        return False


def notify_interview_scheduled(company: str, role: str) -> bool:
    """
    Notify user about scheduled interview.
    
    Args:
        company: Company name
        role: Job role
    
    Returns:
        True if notification sent, False otherwise
    """
    message = generate_whatsapp_message("interview_scheduled", company, role)
    
    if not message:
        return False
    
    logger.info(f"📱 Interview notification: {company} - {role}")
    return send_whatsapp_notification(message)


def notify_offer_received(company: str, role: str) -> bool:
    """
    Notify user about received offer.
    
    Args:
        company: Company name
        role: Job role
    
    Returns:
        True if notification sent, False otherwise
    """
    message = generate_whatsapp_message("offer_received", company, role)
    
    if not message:
        return False
    
    logger.info(f"📱 Offer notification: {company} - {role}")
    return send_whatsapp_notification(message)


def notify_follow_up_reminder(company: str, role: str, days_since_update: int) -> bool:
    """
    Notify user to follow up on pending application.
    
    Args:
        company: Company name
        role: Job role
        days_since_update: Days since last update
    
    Returns:
        True if notification sent, False otherwise
    """
    message = generate_whatsapp_message("follow_up_reminder", company, role, days_since_update)
    
    if not message:
        return False
    
    logger.info(f"📱 Follow-up reminder: {company} - {role} ({days_since_update} days)")
    return send_whatsapp_notification(message)


def should_send_notification(event_type: str, status: str = "", 
                            days_since_update: int = 0) -> bool:
    """
    Determine if a notification should be sent based on event and context.
    
    Args:
        event_type: "interview", "offer", "applied", "rejected"
        status: Job status
        days_since_update: Days since last update
    
    Returns:
        True if notification should be sent, False otherwise
    """
    
    # Always notify for interview and offer
    if event_type in ["interview", "offer"]:
        return True
    
    # For follow-up reminders:
    # - Applied > 10 days
    # - Interview > 7 days
    if event_type == "follow_up_reminder":
        if status == "Applied" and days_since_update > 10:
            return True
        if status == "Interview" and days_since_update > 7:
            return True
    
    return False


def batch_check_and_notify(jobs_data: list) -> dict:
    """
    Check all jobs and send notifications where needed.
    
    Args:
        jobs_data: List of job records from dashboard
    
    Returns:
        Dict with notification stats
    """
    stats = {
        "interviews_notified": 0,
        "offers_notified": 0,
        "followups_notified": 0,
        "total_sent": 0,
        "failed": 0
    }
    
    for job in jobs_data:
        try:
            company = job.get("Company", "")
            role = job.get("Role", "")
            status = job.get("Status", "")
            days_since = int(job.get("Days_Since_Update", 0))
            
            # Skip if no company/role
            if not company or not role:
                continue
            
            # Check for interview notification
            if status == "Interview" and should_send_notification("interview", status):
                if notify_interview_scheduled(company, role):
                    stats["interviews_notified"] += 1
                    stats["total_sent"] += 1
                else:
                    stats["failed"] += 1
            
            # Check for offer notification
            elif status == "Offer" and should_send_notification("offer", status):
                if notify_offer_received(company, role):
                    stats["offers_notified"] += 1
                    stats["total_sent"] += 1
                else:
                    stats["failed"] += 1
            
            # Check for follow-up reminder
            elif should_send_notification("follow_up_reminder", status, days_since):
                if notify_follow_up_reminder(company, role, days_since):
                    stats["followups_notified"] += 1
                    stats["total_sent"] += 1
                else:
                    stats["failed"] += 1
        
        except Exception as e:
            logger.error(f"Error processing notification for {company}: {e}")
            stats["failed"] += 1
    
    return stats


# Test function
if __name__ == "__main__":
    # Test message generation
    print("Testing WhatsApp notification generation...\n")
    
    msg1 = generate_whatsapp_message("interview_scheduled", "Google", "Senior SWE")
    print(f"Interview Alert:\n{msg1}\n")
    
    msg2 = generate_whatsapp_message("offer_received", "Microsoft", "Cloud Architect")
    print(f"Offer Alert:\n{msg2}\n")
    
    msg3 = generate_whatsapp_message("follow_up_reminder", "Amazon", "Data Scientist", 12)
    print(f"Follow-up Reminder:\n{msg3}\n")
    
    print("Note: To actually send, ensure .env has valid Twilio credentials.")
